MyEShop/Areas/Admin/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DataLayer;
using InsertShowImage;
using KooyWebApp_MVC.Classes;


namespace MyEShop.Areas.Admin.Controllers
{
    public class ProductsController : Controller
    {
        private MvcEShop_DBEntities db = new MvcEShop_DBEntities();

        // GET: Admin/Products
        public ActionResult Index()
        {
            return View(db.Products.ToList());
        }

        // GET: Admin/Products/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Products products = db.Products.Find(id);
            if (products == null)
            {
                return HttpNotFound();
            }
            return View(products);
        }

        // GET: Admin/Products/Create
        public ActionResult Create()
        {
            ViewBag.Groups = db.Product_Groups.ToList();
            return View();
        }

        // POST: Admin/Products/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ProductID,ProductTitle,ProductShortDesc,ProductText,ProductPrice,ProductImageName,ProductRecordDate,ProductModificationDate")] Products products, List<int> selectedGroups, HttpPostedFileBase imageProduct, string tags)
        {
            if (ModelState.IsValid)
            {
                if (selectedGroups == null)
                {
                    ViewBag.ErrorSelectedGroup = true;
                    ViewBag.Groups = db.Product_Groups.ToList();
                    return View(products);
                }
                products.ProductImageName = "download.png";
                if (imageProduct!=null && imageProduct.IsImage())
                {
                    products.ProductImageName = Guid.NewGuid().ToString() + Path.GetExtension(imageProduct.FileName);
                    imageProduct.SaveAs(Server.MapPath("/Images/ProductImages/" + products.ProductImageName));
                    ImageResizer img = new ImageResizer();
                    img.Resize(Server.MapPath("/Images/ProductImages/" + products.ProductImageName ),
                        Server.MapPath("/Images/ProductImages/Thumb/" + products.ProductImageName));
                   
                }
                products.RecordDate = DateTime.Now;
                products.ModificationDate = DateTime.Now;
                db.Products.Add(products);
                foreach (int selectedGroup in selectedGroups)
                {
                   db.Product_Selected_Groups.Add(new Product_Selected_Groups()
                    {
                        ProductID = products.ProductID,
                        GroupID = selectedGroup,
                        RecordDate=DateTime.Now,
                        ModificationDate = DateTime.Now
                    });
                }
                if (!string.IsNullOrEmpty(tags))
                {
                    string[] tag = tags.Split(',');
                    foreach (string t in tag)
                    {
                        db.Product_Tags.Add(new Product_Tags()
                        {
                            ProductID = products.ProductID,
                            ProductTag = t.Trim(),
                            RecordDate = DateTime.Now,
                            ModificationDate = DateTime.Now
                        });
                    }
                }
          
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Groups = db.Product_Groups.ToList();
            return View(products);
        }

        // GET: Admin/Products/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Products products = db.Products.Find(id);
            if (products == null)
            {
                return HttpNotFound();
            }
            ViewBag.SelectedGroups = products.Product_Selected_Groups.ToList();
            ViewBag.Groups = db.Product_Groups.ToList();
            ViewBag.Tags = string.Join(",", products.Product_Tags.Select(t=>t.ProductTag).ToList());
            return View(products);
        }

        // POST: Admin/Products/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ProductID,ProductTitle,ProductShortDesc,ProductText,ProductPrice,ProductImageName,ProductRecordDate,ProductModificationDate")] Products products, List<int> selectedGroups, HttpPostedFileBase imageProduct, string tags)
        {
            if (ModelState.IsValid)
            {
                if (imageProduct != null && imageProduct.IsImage())
                {
                    if (products.ProductImageName != "download.png")
                    {
                        System.IO.File.Delete(Server.MapPath("/Images/ProductImages/" + products.ProductImageName));
                        System.IO.File.Delete(Server.MapPath("/Images/ProductImages/Thumb" + products.ProductImageName));
                    }
                    products.ProductImageName = Guid.NewGuid().ToString() + Path.GetExtension(imageProduct.FileName);
                    imageProduct.SaveAs(Server.MapPath("/Images/ProductImages/" + products.ProductImageName));
                    ImageResizer img = new ImageResizer();
                    img.Resize(Server.MapPath("/Images/ProductImages/" + products.ProductImageName),
                        Server.MapPath("/Images/ProductImages/Thumb/" + products.ProductImageName));

                }
                db.Entry(products).State = EntityState.Modified;
                products.RecordDate = DateTime.Now;
                products.ModificationDate = DateTime.Now;

                db.Product_Tags.Where(t => t.ProductID == products.ProductID).ToList().ForEach(t=>db.Product_Tags.Remove(t));
                if (!string.IsNullOrEmpty(tags))
                {
                    string[] tag = tags.Split(',');
                    foreach (string t in tag)
                    {
                        db.Product_Tags.Add(new Product_Tags()
                        {
                            ProductID = products.ProductID,
                            ProductTag = t.Trim(),
                            RecordDate = DateTime.Now,
                            ModificationDate = DateTime.Now
                        });
                    }
                }

                db.Product_Selected_Groups.Where(g => g.ProductID == products.ProductID).ToList().ForEach(g => db.Product_Selected_Groups.Remove(g));
                foreach (int selectedGroup in selectedGroups)
                {
                    db.Product_Selected_Groups.Add(new Product_Selected_Groups()
                    {
                        ProductID = products.ProductID,
                        GroupID = selectedGroup,
                        RecordDate = DateTime.Now,
                        ModificationDate = DateTime.Now
                    });
                }

                ViewBag.SelectedGroups = products.Product_Selected_Groups.ToList();
                ViewBag.Groups = db.Product_Groups.ToList();
                ViewBag.Tags = tags;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(products);
        }

        // GET: Admin/Products/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Products products = db.Products.Find(id);
            if (products == null)
            {
                return HttpNotFound();
            }
            return View(products);
        }

        // POST: Admin/Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Products products = db.Products.Find(id);
            db.Products.Remove(products);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult Gallery(int id)
        {
            ViewBag.Galleries = db.Product_Galleries.Where(p => p.ProductID == id).ToList();
            return View(new Product_Galleries()
            {
                ProductID=id

            }
                
                );
        }
        [HttpPost]
        public ActionResult Gallery(Product_Galleries galleries,HttpPostedFileBase imgUp)
        {
            if (ModelState.IsValid)
            {
                if (imgUp !=null && imgUp.IsImage())
                {
                    galleries.GalleryImageName = Guid.NewGuid().ToString() + Path.GetExtension(imgUp.FileName);
                    imgUp.SaveAs(Server.MapPath("/Images/ProductImages/" + galleries.GalleryImageName));
                    ImageResizer img = new ImageResizer();
                    img.Resize(Server.MapPath("/Images/ProductImages/" + galleries.GalleryImageName),
                    Server.MapPath("/Images/ProductImages/Thumb" + galleries.GalleryImageName));
                    galleries.RecordDate = DateTime.Now;
                    galleries.ModificationDate = DateTime.Now;

MyEShop/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DataLayer;
using DataLayer.ViewModels;

namespace MyEShop.Controllers
{
    public class ProductController : Controller
    {
        MvcEShop_DBEntities db = new MvcEShop_DBEntities();
  
        // GET: Product
        public ActionResult ShowGroups()
        {
            return PartialView(db.Product_Groups.ToList());
        }
    }
}

MyEShop/Areas/Admin/Views/Products/Create.cshtml
@using DataLayer
@model DataLayer.Products

@{
    ViewBag.Title = "Create";
}

<h2>Create Product</h2>
<div class="row">
    @using (Html.BeginForm("Create", "Products", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <div class="col-md-8">
            @Html.AntiForgeryToken()
            @if (ViewBag.ErrorSelectedGroup == true)
            {
                <div class="alert alert-danger"> Please Select a Groups</div>
            }

            <div class="form-horizontal">

                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.ProductTitle, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.ProductTitle, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.ProductTitle, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.ProductShortDesc, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.ProductShortDesc, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.ProductShortDesc, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.ProductText, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.ProductText, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.ProductText, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.ProductPrice, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.ProductPrice, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.ProductPrice, "", new { @class = "text-danger" })
                    </div>
                </div>


                <div class="form-group">
                    <span class="control-label col-md-2">Keyword</span>
                    <div class="col-md-10">
                        <input type="text" name="tags" class="form-control" placeholder="Separate keywords with , " />
                    </div>
                </div>


                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Create Product" class="btn btn-success" />
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class=" panel panel-primary">
                <div class=" panel-heading ">Select Groups</div>
                <div class=" panel-body ">
                    <img id="imgpreviewProduct" style="margin: 8px auto" class="thumbnails-image" src="~/Images/ProductImages/download.png" />
                    <div class="form-group">
                        @Html.LabelFor(model => model.ProductImageName, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            <input type="file" id="imageProduct" name="imageProduct" />
                            @Html.ValidationMessageFor(model => model.ProductImageName, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
            </div>
            <div class=" panel panel-primary">
                <div class=" panel-heading ">Select Image Product</div>
                <div class=" panel-body ">
                    @{
                        List<Product_Groups> groups = ViewBag.Groups;

                        <ul>
                            @foreach (var group in groups.Where(g => g.ParentID == null))
                            {
                                <li>
                                    <input type="checkbox" name="selectedGroups" value="@group.GroupID" /> <span>@group.GroupTitle</span>
                                    @if (groups.Any(g => g.ParentID == group.GroupID))
                                    {
                                        <ul>
                                            @foreach (var subGroup in groups.Where(g => g.ParentID == group.GroupID))
                                            {
                                                <li>
                                                    <input type="checkbox" name="selectedGroups" value="@subGroup.GroupID" /> <span>@subGroup.GroupTitle</span>
                                                </li>
                                            }
                                        </ul>
                                    }
                                </li>
                            }
                        </ul>
                    }
                </div>
            </div>
        </div>
    }
</div>
<div>
    @Html.ActionLink("Back to List Products", "Index")
</div>
@section Scripts
{
    <script>
        function readURL(input) {

            if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function (e) {
                    $('#imgPreviewProduct').attr('src', e.target.result);
                }

                reader.readAsDataURL(input.files[0]);
            }
        }

        $("#imageProduct").change(function () {
            readURL(this);
        });
    </script>
    <script src="/ckeditor/ckeditor.js"></script>
    <script src="/ckeditor/adapters/jquery.js"></script>
    <script>
        $(function () {
            $('#Text').ckeditor();
        });
    </script>
}

MyEShop/Areas/Admin/Views/Products/Delete.cshtml
@model DataLayer.Products

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Products</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ProductTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProductShortDesc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductShortDesc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProductText)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductText)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProductPrice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductPrice)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProductImageName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductImageName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RecordDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RecordDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ModificationDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModificationDate)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

MyEShop/Areas/Admin/Views/Products/Details.cshtml
@model DataLayer.Products

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Products</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ProductTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProductShortDesc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductShortDesc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProductText)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductText)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProductPrice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductPrice)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProductImageName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductImageName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RecordDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RecordDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ModificationDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModificationDate)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ProductID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

MyEShop/Areas/Admin/Views/Products/Edit.cshtml
@using DataLayer
@model DataLayer.Products

@{
    ViewBag.Title = "Edit";
    List<Product_Selected_Groups> selectedGroup = ViewBag.SelectedGroups;
}

<h2>Edit Product</h2>
<div class="row">
    @using (Html.BeginForm("Edit", "Products", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.HiddenFor(m => m.ProductID)
        @Html.HiddenFor(m => m.ProductImageName)
        @Html.HiddenFor(m => m.RecordDate)

        <div class="col-md-8">
            @Html.AntiForgeryToken()
            @if (ViewBag.ErrorSelectedGroup == true)
            {
                <div class="alert alert-danger"> Please Select a Groups</div>
            }

            <div class="form-horizontal">

                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.ProductTitle, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.ProductTitle, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.ProductTitle, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.ProductShortDesc, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.ProductShortDesc, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.ProductShortDesc, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.ProductText, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.ProductText, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.ProductText, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.ProductPrice, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.ProductPrice, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.ProductPrice, "", new { @class = "text-danger" })
                    </div>
                </div>


                <div class="form-group">
                    <span class="control-label col-md-2">Keyword</span>
                    <div class="col-md-10">
                        <input type="text" name="tags" value="@ViewBag.Tags " class="form-control" placeholder="Separate keywords with , " />
                    </div>
                </div>


                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Edit Product" class="btn btn-warning" />
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class=" panel panel-primary">
                <div class=" panel-heading ">Select Groups</div>
                <div class=" panel-body ">
                    <img id="imgpreviewProduct" style="margin: 8px auto" class="thumbnails-image" src="~/Images/ProductImages/@Model.ProductImageName" />
                    <div class="form-group">
                        @Html.LabelFor(model => model.ProductImageName, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            <input type="file" id="imageProduct" name="imageProduct" />
                            @Html.ValidationMessageFor(model => model.ProductImageName, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
            </div>
            <div class=" panel panel-primary">
                <div class=" panel-heading ">Select Image Product</div>
                <div class=" panel-body ">
                    @{
                        List<Product_Groups> groups = ViewBag.Groups;

                        <ul>
                            @foreach (var group in groups.Where(g => g.ParentID == null))
                            {
                                <li>
                                    <input type="checkbox" @((selectedGroup.Any(g => g.GroupID == group.GroupID)) ? "checked" : "") name="selectedGroups" value="@group.GroupID" /> <span>@group.GroupTitle</span>
                                    @if (groups.Any(g => g.ParentID == group.GroupID))
                                    {
                                        <ul>
                                            @foreach (var subGroup in groups.Where(g => g.ParentID == group.GroupID))
                                            {
                                                <li>
                                                    <input type="checkbox" @((selectedGroup.Any(g => g.GroupID == subGroup.GroupID)) ? "checked" : "") name="selectedGroups" value="@subGroup.GroupID" /> <span>@subGroup.GroupTitle</span>
                                                </li>
                                            }
                                        </ul>
                                    }
                                </li>
                            }
                        </ul>
                    }
                </div>
            </div>
        </div>
    }
</div>
<div>
    @Html.ActionLink("Back to List Products", "Index")
</div>
@section Scripts
{
    <script>
        function readURL(input) {

            if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function (e) {
                    $('#imgPreviewProduct').attr('src', e.target.result);
                }

                reader.readAsDataURL(input.files[0]);
            }
        }

        $("#imageProduct").change(function () {
            readURL(this);
        });
    </script>
    <script src="/ckeditor/ckeditor.js"></script>
    <script src="/ckeditor/adapters/jquery.js"></script>
    <script>
        $(function () {
            $('#Text').ckeditor();
        });
    </script>
}

MyEShop/Areas/Admin/Views/Products/Gallery.cshtml
@model DataLayer.Product_Galleries

@{
    ViewBag.Title = "Gallery";
}

<h2>Gallery</h2>
<div class="row">
@using (Html.BeginForm("Gallery", "Products", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(m => m.ProductID)

    <div class="col-md-4">
        <div class="form-horizontal">
            <h4>Gallery Product</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group">
                @Html.LabelFor(model => model.GalleryTitle, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.GalleryTitle, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.GalleryTitle, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.GalleryImageName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <input type="file" name="imgUp" value="" />
                    @Html.ValidationMessageFor(model => model.GalleryImageName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>

        </div>
    </div>



    <div class="col-md-8">
        @{
//List<Product_Galleries> list = ViewBag.Galleries;
            <table class="table table-bordered">
                <tr>
                    <trh>Picture</trh>
                    <trh>Title</trh>
                    <trh></trh>
                </tr>
                @*@foreach (var item in list)
                {
                    <tr></tr>
                }*@

            </table>

        }

    </div>
}
</div>

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

MyEShop/Areas/Admin/Views/Products/Index.cshtml
@model IEnumerable<DataLayer.Products>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    <a class="btn btn-primary" href=" @Url.Action("Create")">Create New Product</a>
</p>
<table class="table table-bordered">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ProductImageName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ProductTitle)
        </th>
        <th>
            Products Group
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ProductPrice)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RecordDate)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            <img class="t" src="~/Images/ProductImages/Thumb"/>
        </td>

        <td>
            @Html.DisplayFor(modelItem => item.ProductTitle)
        </td>
        <td>
            @if (item.Product_Selected_Groups.Any())
            {
                <ol>
                    @foreach (var group in item.Product_Selected_Groups )
                    {
                       <li>
                           @group.Product_Groups.GroupTitle

                      </li>
                    }
                </ol>
            }
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ProductPrice)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.RecordDate)
        </td>
        <td>
            <a class="btn btn-default btn-xs" href="#">Product Features</a>
            <a class="btn btn-info btn-xs" href="#">Product Gallery</a>
            <a class="btn btn-warning btn-xs" href="@Url.Action("Edit",new {id=item.ProductID })">Product Edit</a>
            <a class="btn btn-danger btn-xs" href="@Url.Action("Delete",new {id=item.ProductID })">Product Delete</a>

        </td>
    </tr>
}

</table>