MyEShop/Areas/Admin/Controllers/SlidersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DataLayer;


namespace MyEShop.Areas.Admin.Controllers
{
    public class SlidersController : Controller
    {
        private MvcEShop_DBEntities db = new MvcEShop_DBEntities();

        // GET: Admin/Sliders
        public ActionResult Index()
        {
            return View(db.Slider.ToList());
        }

        // GET: Admin/Sliders/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Slider slider = db.Slider.Find(id);
            if (slider == null)
            {
                return HttpNotFound();
            }
            return View(slider);
        }

        // GET: Admin/Sliders/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/Sliders/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "SliderID,SliderTitle,SliderUrl,SliderImageName,SliderStartDate,SliderEndTime,SliderIsActive,RegisterDate,ModificationDate")] Slider slider, HttpPostedFileBase imgUp)
        {
            if (ModelState.IsValid)
            {
                if (imgUp == null)
                {
                    ModelState.AddModelError("SliderImageName", "Please select Image");
                    return View(slider);
                }
                slider.SliderImageName = Guid.NewGuid().ToString() + System.IO.Path.GetExtension(imgUp.FileName);
                imgUp.SaveAs(Server.MapPath("/Images/Slider/" + slider.SliderImageName));

                slider.SliderStartDate = DateTime.Now;
                slider.SliderEndTime = DateTime.Now;
                slider.RegisterDate = DateTime.Now;
                slider.ModificationDate = DateTime.Now;

                db.Slider.Add(slider);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(slider);
        }

        // GET: Admin/Sliders/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Slider slider = db.Slider.Find(id);
            if (slider == null)
            {
                return HttpNotFound();
            }
            return View(slider);
        }

        // POST: Admin/Sliders/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "SliderID,SliderTitle,SliderUrl,SliderImageName,SliderStartDate,SliderEndTime,SliderIsActive,RegisterDate,ModificationDate")] Slider slider, HttpPostedFileBase imgUp)
        {
            if (ModelState.IsValid)
            {
                if (imgUp!=null)
                {
                    System.IO.File.Delete(Server.MapPath("/Images/Slider/" + slider.SliderImageName));
                    slider.SliderImageName = Guid.NewGuid().ToString() + System.IO.Path.GetExtension(imgUp.FileName);
                    imgUp.SaveAs(Server.MapPath("/Images/Slider/" + slider.SliderImageName));
                }
                db.Entry(slider).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(slider);
        }

        // GET: Admin/Sliders/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Slider slider = db.Slider.Find(id);
            if (slider == null)
            {
                return HttpNotFound();
            }
            return View(slider);
        }

        // POST: Admin/Sliders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Slider slider = db.Slider.Find(id);
            System.IO.File.Delete(Server.MapPath("/Images/Slider/" + slider.SliderImageName));
            db.Slider.Remove(slider);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MyEShop/Areas/Admin/Views/Sliders/Create.cshtml
@model DataLayer.Slider

@{
    ViewBag.Title = "Create Slider";
}


@using (Html.BeginForm("Create", "Sliders",FormMethod.Post, new { enctype="multipart/form-data"}))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Slider</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.SliderTitle, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.SliderTitle, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.SliderTitle, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.SliderUrl, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.SliderUrl, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.SliderTitle, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.SliderImageName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" name="imgUp" />
            @Html.ValidationMessageFor(model => model.SliderImageName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.SliderStartDate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.SliderStartDate)
            @Html.ValidationMessageFor(model => model.SliderStartDate, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.SliderEndTime, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.SliderEndTime)
            @Html.ValidationMessageFor(model => model.SliderEndTime, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.SliderIsActive, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.SliderIsActive)
                @Html.ValidationMessageFor(model => model.SliderIsActive, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>



    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create Slider" class="btn btn-success" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>



@section Scripts
{
    <link href="http://cdn.kendostatic.com/2013.2.918/styles/kendo.common.min.css" rel="stylesheet" />
    <link href="http://cdn.kendostatic.com/2013.2.918/styles/kendo.default.min.css" rel="stylesheet" />
    <script src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
    <script src="~/Areas/Admin/Content/js/kendo.all.min.js"></script>

    <script>
        $(document).ready(function () {

            // create DatePicker from input HTML element
            $("#SliderStartDate").kendoDatePicker();
            $("#SliderEndTime").kendoDatePicker();

        });
    </script>


}

MyEShop/Areas/Admin/Views/Sliders/Delete.cshtml
@model DataLayer.Slider

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Slider</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.SliderTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SliderTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SliderImageName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SliderImageName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SliderStartDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SliderStartDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SliderEndTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SliderEndTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SliderIsActive)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SliderIsActive)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RegisterDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RegisterDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ModificationDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModificationDate)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

MyEShop/Areas/Admin/Views/Sliders/Details.cshtml
@model DataLayer.Slider

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Slider</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.SliderTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SliderTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SliderImageName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SliderImageName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SliderStartDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SliderStartDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SliderEndTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SliderEndTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SliderIsActive)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SliderIsActive)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RegisterDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RegisterDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ModificationDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModificationDate)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.SliderID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

MyEShop/Areas/Admin/Views/Sliders/Edit.cshtml
@model DataLayer.Slider

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm("Edit", "Sliders", FormMethod.Post, new { enctype = "multipart/form-data" }))

{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Slider</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.SliderID)
    @Html.HiddenFor(model => model.SliderImageName)


    <div class="form-group">
        @Html.LabelFor(model => model.SliderTitle, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.SliderTitle, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.SliderTitle, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.SliderUrl, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.SliderUrl, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.SliderTitle, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.SliderImageName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" name="imgUp" />
            @Html.ValidationMessageFor(model => model.SliderImageName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.SliderStartDate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="text" name="StartDate" id="StartDate" value="@Model.SliderStartDate.ToString("yyyy/MM/dd")" />
            @Html.ValidationMessageFor(model => model.SliderStartDate, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.SliderEndTime, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">

            <input type="text" name="EndTime" id="EndTime" value="@Model.SliderEndTime.ToString("yyyy/MM/dd")" />
            @Html.ValidationMessageFor(model => model.SliderEndTime, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.SliderIsActive, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.SliderIsActive)
                @Html.ValidationMessageFor(model => model.SliderIsActive, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>



    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Edit" class="btn btn-warning" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts
{
    <link href="http://cdn.kendostatic.com/2013.2.918/styles/kendo.common.min.css" rel="stylesheet" />
    <link href="http://cdn.kendostatic.com/2013.2.918/styles/kendo.default.min.css" rel="stylesheet" />
    <script src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
    <script src="~/Areas/Admin/Content/js/kendo.all.min.js"></script>

    <script>
        $(document).ready(function () {

            // create DatePicker from input HTML element
            $("#SliderStartDate").kendoDatePicker();
            $("#SliderEndTime").kendoDatePicker();

        });
    </script>


}}

MyEShop/Areas/Admin/Views/Sliders/Index.cshtml
@model IEnumerable<DataLayer.Slider>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.SliderTitle)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.SliderStartDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SliderEndTime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SliderIsActive)
        </th>
 
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.SliderTitle)
        </td>

        <td>
            @Html.DisplayFor(modelItem => item.SliderStartDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SliderEndTime)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SliderIsActive)
        </td>
    
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.SliderID }) |
            @Html.ActionLink("Details", "Details", new { id=item.SliderID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.SliderID })
        </td>
    </tr>
}

</table>