MyEShop/Areas/Admin/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DataLayer;
using InsertShowImage;
using KooyWebApp_MVC.Classes;


namespace MyEShop.Areas.Admin.Controllers
{
    public class ProductsController : Controller
    {
        private MvcEShop_DBEntities db = new MvcEShop_DBEntities();

        // GET: Admin/Products
        public ActionResult Index()
        {
            return View(db.Products.ToList());
        }

        // GET: Admin/Products/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Products products = db.Products.Find(id);
            if (products == null)
            {
                return HttpNotFound();
            }
            return View(products);
        }

        // GET: Admin/Products/Create
        public ActionResult Create()
        {
            ViewBag.Groups = db.Product_Groups.ToList();
            return View();
        }

        // POST: Admin/Products/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ProductID,ProductTitle,ProductShortDesc,ProductText,ProductPrice,ProductImageName,ProductRecordDate,ProductModificationDate")] Products products, List<int> selectedGroups, HttpPostedFileBase imageProduct, string tags)
        {
            if (ModelState.IsValid)
            {
                if (selectedGroups == null)
                {
                    ViewBag.ErrorSelectedGroup = true;
                    ViewBag.Groups = db.Product_Groups.ToList();
                    return View(products);
                }
                products.ProductImageName = "download.png";
                if (imageProduct!=null && imageProduct.IsImage())
                {
                    products.ProductImageName = Guid.NewGuid().ToString() + Path.GetExtension(imageProduct.FileName);
                    imageProduct.SaveAs(Server.MapPath("/Images/ProductImages/" + products.ProductImageName));
                    ImageResizer img = new ImageResizer();
                    img.Resize(Server.MapPath("/Images/ProductImages/" + products.ProductImageName ),
                        Server.MapPath("/Images/ProductImages/Thumb/" + products.ProductImageName));
                   
                }
                products.RecordDate = DateTime.Now;
                products.ModificationDate = DateTime.Now;
                db.Products.Add(products);
                foreach (int selectedGroup in selectedGroups)
                {
                   db.Product_Selected_Groups.Add(new Product_Selected_Groups()
                    {
                        ProductID = products.ProductID,
                        GroupID = selectedGroup,
                        RecordDate=DateTime.Now,
                        ModificationDate = DateTime.Now
                    });
                }
                if (!string.IsNullOrEmpty(tags))
                {
                    string[] tag = tags.Split(',');
                    foreach (string t in tag)
                    {
                        db.Product_Tags.Add(new Product_Tags()
                        {
                            ProductID = products.ProductID,
                            ProductTag = t.Trim(),
                            RecordDate = DateTime.Now,
                            ModificationDate = DateTime.Now
                        });
                    }
                }
          
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Groups = db.Product_Groups.ToList();
            return View(products);
        }

        // GET: Admin/Products/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Products products = db.Products.Find(id);
            if (products == null)
            {
                return HttpNotFound();
            }
            ViewBag.SelectedGroups = products.Product_Selected_Groups.ToList();
            ViewBag.Groups = db.Product_Groups.ToList();
            ViewBag.Tags = string.Join(",", products.Product_Tags.Select(t=>t.ProductTag).ToList());
            return View(products);
        }

        // POST: Admin/Products/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ProductID,ProductTitle,ProductShortDesc,ProductText,ProductPrice,ProductImageName,ProductRecordDate,ProductModificationDate")] Products products, List<int> selectedGroups, HttpPostedFileBase imageProduct, string tags)
        {
            if (ModelState.IsValid)
            {
                if (imageProduct != null && imageProduct.IsImage())
                {
                    if (products.ProductImageName != "download.png")
                    {
                        System.IO.File.Delete(Server.MapPath("/Images/ProductImages/" + products.ProductImageName));
                        System.IO.File.Delete(Server.MapPath("/Images/ProductImages/Thumb" + products.ProductImageName));
                    }
                    products.ProductImageName = Guid.NewGuid().ToString() + Path.GetExtension(imageProduct.FileName);
                    imageProduct.SaveAs(Server.MapPath("/Images/ProductImages/" + products.ProductImageName));
                    ImageResizer img = new ImageResizer();
                    img.Resize(Server.MapPath("/Images/ProductImages/" + products.ProductImageName),
                        Server.MapPath("/Images/ProductImages/Thumb/" + products.ProductImageName));

                }
                db.Entry(products).State = EntityState.Modified;
                products.RecordDate = DateTime.Now;
                products.ModificationDate = DateTime.Now;

                db.Product_Tags.Where(t => t.ProductID == products.ProductID).ToList().ForEach(t=>db.Product_Tags.Remove(t));
                if (!string.IsNullOrEmpty(tags))
                {
                    string[] tag = tags.Split(',');
                    foreach (string t in tag)
                    {
                        db.Product_Tags.Add(new Product_Tags()
                        {
                            ProductID = products.ProductID,
                            ProductTag = t.Trim(),
                            RecordDate = DateTime.Now,
                            ModificationDate = DateTime.Now
                        });
                    }
                }

                db.Product_Selected_Groups.Where(g => g.ProductID == products.ProductID).ToList().ForEach(g => db.Product_Selected_Groups.Remove(g));
                foreach (int selectedGroup in selectedGroups)
                {
                    db.Product_Selected_Groups.Add(new Product_Selected_Groups()
                    {
                        ProductID = products.ProductID,
                        GroupID = selectedGroup,
                        RecordDate = DateTime.Now,
                        ModificationDate = DateTime.Now
                    });
                }

                ViewBag.SelectedGroups = products.Product_Selected_Groups.ToList();
                ViewBag.Groups = db.Product_Groups.ToList();
                ViewBag.Tags = tags;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(products);
        }

        // GET: Admin/Products/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Products products = db.Products.Find(id);
            if (products == null)
            {
                return HttpNotFound();
            }
            return View(products);
        }

        // POST: Admin/Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Products products = db.Products.Find(id);
            db.Products.Remove(products);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult Gallery(int id)
        {
            ViewBag.Galleries = db.Product_Galleries.Where(p => p.ProductID == id).ToList();
            return View(new Product_Galleries()
            {
                ProductID=id

            }
                
                );
        }
        [HttpPost]
        public ActionResult Gallery(Product_Galleries galleries,HttpPostedFileBase imgUp)
        {
            if (ModelState.IsValid)
            {
                if (imgUp !=null && imgUp.IsImage())
                {
                    galleries.GalleryImageName = Guid.NewGuid().ToString() + Path.GetExtension(imgUp.FileName);
                    imgUp.SaveAs(Server.MapPath("/Images/ProductImages/" + galleries.GalleryImageName));
                    ImageResizer img = new ImageResizer();
                    img.Resize(Server.MapPath("/Images/ProductImages/" + galleries.GalleryImageName),
                    Server.MapPath("/Images/ProductImages/Thumb" + galleries.GalleryImageName));
                    galleries.RecordDate = DateTime.Now;
                    galleries.ModificationDate = DateTime.Now;

MyEShop/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DataLayer;
using DataLayer.ViewModels;

namespace MyEShop.Controllers
{
    public class ProductController : Controller
    {
        MvcEShop_DBEntities db = new MvcEShop_DBEntities();
  
        // GET: Product
        public ActionResult ShowGroups()
        {
            return PartialView(db.Product_Groups.ToList());
        }
    }
}

MyEShop/Views/Product/ArchiveProduct.cshtml
@using DataLayer
@model IEnumerable<DataLayer.Products>
@{
    ViewBag.Title = "ArchiveProduct";
}

@section Filters
{
    <section class="border-radius ">
        <header><h3> Filters </h3></header>
        <article class="filter">
            <form action="/Archive" id="filterForm">
                <input type="hidden" name="@ViewBag.pageId" id="PageId"  value="PageId" />
                <p>Title</p><p><input type="text" name="title" value="@ViewBag.name" class="form-control" /></p>
                <p>Price from</p><p><input type="number" name="minPrice" value="@ViewBag.minPrice" class="form-control" /></p>
                <p>Price up</p><p><input type="number" name="maxPrice" value="@ViewBag.maxPrice" class="form-control" /></p>
                @{
                    List<Product_Groups> list = ViewBag.Groups;
                    //??Age null bod error nade
                    List<int> selected = ViewBag.SelectedGroups?? new List<int>();
                }
                <p>Filter Groups</p>
                <ul>
                    @foreach (var group in list.Where(g => g.ParentID == null))
                    {
                        <li>
                            <input type="checkbox" name="SelectedGroups" @((selected.Any(s=>s==group.GroupID))?"checked":"") value="@group.GroupID" />
                            <span>@group.GroupTitle </span>
                            @if (list.Any(g=>g.ParentID==group.GroupID))
                            {
                                <ul>
                                    @foreach (var subGroup in list.Where(g => g.ParentID == group.GroupID))
                                    {
                                    <li>
                                        <input type="checkbox" name="SelectedGroups" @((selected.Any(s=>s==subGroup.GroupID))?"checked":"")  value="@subGroup.GroupID" />
                                        <span>@subGroup.GroupTitle </span>
                                    </li>
                                    }
                                </ul>
                            }

                        </li>
                    }
                </ul>
                <input type="submit" name="name" value="Actions" class="btn btn-block btn-primary" />
            </form>

        </article>
    </section>

}


    <section class="last-products">
        <header><h3> Archive Products </h3> <a href="">  </a></header>
        <article>

            @foreach (var item in Model)
            {
                @Html.Partial("_product", item)
            }

            <div class="clearfix"></div>
        </article>
    </section>
@if (ViewBag.PageCount > 1)
{
    <div class="pagination-layer">
        <ul class="pagination">
            @for (int i = 1; i <= ViewBag.PageCount; i++)
            {
                <li><a onclick="changePage(I)" href="#">@i</a></li>

            }
        </ul>
    </div>
}

<script>
    function changePage(pageId)
    {
        $('#PageId').val(PageId);
        $('#filterForm').subm ;
    }
</script>

MyEShop/Views/Product/CreateComment.cshtml
@model DataLayer.Product_Comments

@using (Ajax.BeginForm("CreateComment", "Product", FormMethod.Post, new AjaxOptions()
{
    OnSuccess = "successComment",
    UpdateTargetId = "listComment"

}))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(m => m.ProductID)
    @Html.HiddenFor(m => m.CommentParentID)
    <div class="col-md-5">
        <div class="form-group">
            @Html.TextBoxFor(m => m.UserName, new { @class = "form-control", placeholder = "Insert your Name" })
            @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })

        </div>
        <div class="form-group">
            @Html.TextBoxFor(m => m.UserEmail, new { @class = "form-control", placeholder = "Insert your Email" })
            @Html.ValidationMessageFor(model => model.UserEmail, "", new { @class = "text-danger" })

        </div>
        <div class="form-group">
            @Html.TextBoxFor(m => m.UserWebSite, new { @class = "form-control", placeholder = "Insert your WebSite" })
        </div>
    </div>
    <div class="col-md-7">
        @Html.TextAreaFor(m => m.Comment, new { @class = "form-control", placeholder = "Insert your Comment" })
        @Html.ValidationMessageFor(model => model.Comment, "", new { @class = "text-danger" })

        <input class="btn btn-primary" value="ثبت دیدگاه ارزشمند شما" type="submit">
    </div>
    <div class="clearfix"></div>

}

MyEShop/Views/Product/LastProduct.cshtml
@model IEnumerable<DataLayer.Products>

<section class="last-products">
    <header><h3> New Products </h3> <a href="">Archive</a></header>
    <article>

        @foreach (var item in Model)
        {
            @Html.Partial("_product",item)
        }

        <div class="clearfix"></div>
    </article>
</section>

MyEShop/Views/Product/ShowComments.cshtml
@model IEnumerable<DataLayer.Product_Comments>

@foreach (var item in Model.Where(c => c.CommentParentID == null))
{
<li>
    <a onclick="ReplyComment(@item.CommentID)" class="reply-button">Answer</a>

    <img src="/Content/img/avatar.jpg" width="65">
    <div>
        <h5>ارسال شده از : @item.UserName در تاریخ : @item.RegisterDate.ToString("yyyy/MM/dd") </h5>
        <p>
            @item.Comment
        </p>
    </div>
    <div class="clearfix"></div>
    @if (Model.Any(c => c.CommentParentID == item.CommentID))
    {
        <ul>
            @foreach (var sub in Model.Where(c => c.CommentParentID == item.CommentID))
            {
                <li>
                    <img src="/Content/img/avatar.jpg" width="65">
                    <div>
                        <h5>ارسال شده از : @sub.UserName در تاریخ : @sub.RegisterDate.ToString("yyy/MM/dd") </h5>
                        <p>
                            @sub.Comment
                        </p>
                    </div>
                    <div class="clearfix"></div>
                </li>
            }

        </ul>
    }

</li>
}

MyEShop/Views/Product/ShowGroups.cshtml
@model IEnumerable<DataLayer.Product_Groups>
<section class="border-radius category-side">
    <header><h3> دسته بندی ها </h3></header>
    <article>
        <ul class="category-menu">
            @foreach (var group in Model.Where(g => g.ParentID == null))
            {
            <li>
                <h2><a href="">@group.GroupTitle  </a></h2>
                @if (Model.Any(g => g.ParentID == group.GroupID))
                {
                <ul class="child-category-menu">
                    @foreach (var subGroup in Model.Where(g => g.ParentID == group.GroupID))
                    {
                        <li><h2><a href="">@subGroup.GroupTitle </a> <span>(0)</span></h2></li>
                    }
                </ul>
                }

            </li>
            }

        </ul>
    </article>
</section>

MyEShop/Views/Product/ShowProduct.cshtml
@using DataLayer
@using DataLayer.ViewModels
@model DataLayer.Products
@{
    ViewBag.Title = Model.ProductTitle;
}

<section class="single-page">
    <header><h3> @Model.ProductTitle </h3> </header>
    <article>
        <!-- Detail -->
        <div class="col-md-8 col-sm-12 col-xs-12 pull-left detail-product">
            <div>
                <span> قیمت :@Model.ProductPrice.ToString("#,0") </span>
                <a onclick="AddToCart(@Model.ProductID)" class="add-to-card-link border-radius"> افزودن به سبد خرید </a>
            </div>
            <p>@Model.ProductShortDesc</p>
        </div>
        <!-- End Detail -->
        <!-- Gallery -->
        <div class="col-md-4 col-sm-12 col-xs-12 pull-right product-gallery">
            <div class="large-image border-radius">
                <img class="border-radius" src="~/Images/ProductImages/@Model.ProductImageName">
            </div>
            @if (Model.Product_Galleries.Any())
            {
                <div class="thumbnails-image">
                    <div class="row">
                        @foreach (var item in Model.Product_Galleries)
                        {
                            <div class="col-md-3 col-sm-3 col-xs-4 border-radius"><img class="border-radius" alt="@item.GalleryTitle" src="~/Images/ProductImages/@item.GalleryImageName"></div>

                        }

                        <div class="clearfix"></div>
                    </div>
                </div>

            }
        </div>
        <!-- End Gallery -->
        <div class="clearfix"></div>
    </article>
</section>


<div class="tabs-product margin-top-25">
    <ul class="nav nav-tabs">
        <li class="active"><a data-toggle="tab" href="#main-content"> توضیحات کامل </a></li>
        <li><a data-toggle="tab" href="#properties"> ویژگی ها </a></li>
        <li><a data-toggle="tab" href="#comments"> نظرات کاربران </a></li>
    </ul>

    <div class="tab-content ">

        <!-- description -->
        <div id="main-content" class="tab-pane fade in active">
            @Html.Raw(Model.ProductText)
        </div>
        <!-- End description -->
        <!-- Chart -->
        <div id="properties" class="tab-pane fade">

            @if (ViewBag.Productfeatures != null)
            {
                List<ShowProductFeatureViewModel> list = ViewBag.Productfeatures;

                <ul>
                    @foreach (var item in list)
                    {
                        <li>@item.FeatureTitle:@string.Join(",", item.Values)</li>
                    }

                </ul>
            }

        </div>
        <!-- End Chart -->
        <!-- Comment -->
        <div id="comments" class="tab-pane fade">
            <div class="comment-layer" id="commentProduct">
                @Html.Action("CreateComment")
                <ul class="comment-list" id="listComment">
                    @Html.Action("ShowComments")
                </ul>
            </div>

        </div>
        <!-- End Comment -->



    </div>
</div>

<section class="border-radius tags-layer">
    @foreach (var item in Model.ProductTags)
    {
        <a href="/Search?q=@item.Tag">@item.ProductTag</a>
    }
</section>


<script>
    function successComment() {
        $("#UserName").val("");
        $("#UserEmail").val("");
        $("#UserWebSite").val("");
        $("#Comment").val("");
        $("#CommentParentID").val("");
    }

    function ReplyComment(id) {
        $("#CommentParentID").val(id);
        $("html, body").delay(2000).animate({ scrollTop: $('#CommentParentID').offset().top }, 2000);
    }
</script>